In [1]:
import numpy as np

## Вектор

In [2]:
s = np.array([33, 65, 50, 45])
s

array([33, 65, 50, 45])

In [3]:
s[2]

50

In [5]:
len(s)

4

In [6]:
a = np.array([10, 8, 5, 1])
b = np.array([5, 15, 9, 7])
a + b

array([15, 23, 14,  8])

In [7]:
a - b

array([ 5, -7, -4, -6])

In [8]:
a = np.array([120, 45, 68])
omega = 0.2
c = a * omega
c

array([24. ,  9. , 13.6])

In [13]:
a = np.array([120, 150, 190])
b = np.array([130, 130, 130])
c = np.array([2, 3, 2.5])
c = c*72
s = a+b+c
s

array([394., 496., 500.])

In [14]:
p = np.array([2, 4, 5])
v = np.array([8, 10, 2])
s = np.array([0, 12, 7])
omega1 = 500
omega2 = 100
omega3 = 0
u = omega1*p + omega2*v + omega3*s
u

array([1800, 3000, 2700])

In [16]:
a = np.array([3, 4, 5, 9])
b = np.array([1, 5, 3, 6])
s = b*400 - a*200
s

array([-200, 1200,  200,  600])

In [24]:
# В Python скалярное произведение векторов вычисляется при помощи функции np.dot():
a = np.array([65, 70, 120, 30])
w = np.array([0.4, 0.4, 0.2, 0.8])
np.dot(a, w)
s = a@w
s

102.0

#### Практика

In [18]:
# нулевой массив указанной длины 
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
# массив из единиц указанной длины
np.ones(3)

array([1., 1., 1.])

In [21]:
# массив из чисел по порядку
np.arange(10, 50, 5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
# случайный массив 10 случайных чисел от -4 до 2-х
np.random.randint(-4, 2, 10)

In [22]:
import pandas as pd
data = [65, 70, 120, 35]
s = pd.Series(data)
x = s.values
x

array([ 65,  70, 120,  35], dtype=int64)

In [25]:
Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})

In [33]:
ar = Hut_Paradise_DF.values
ar[4]

array([40, 33,  1,  6, 20, 16], dtype=int64)

In [34]:
ar[:,3] # вектор этажей

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5], dtype=int64)

In [36]:
ar[:,1]-ar[:,5] # нежилая площадь

array([13, 12, 15, 13, 17,  9, 20, 15, 25], dtype=int64)

In [38]:
a = np.array([10, 20, 30, 15, 5, 40, 20, 8, 20])
s = ar[:,4]@a
s

1348

In [42]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])
с = 2*v-3*w
с

array([-3, 14,  3,  4,  2])

In [43]:
c @ u == 0

True

## Матрица

In [45]:
A = np.array([
    [1, -5, 3], 
    [2, 2, 1],
    [0, 3, 1],
    [2, 4, 12]
])
A.shape
## (4, 3)
print('a_23=', A[1, 2], 'a_32=', A[2, 1], 'a_33=', A[2,2])

a_23= 1 a_32= 3 a_33= 1


In [46]:
A = np.matrix("1, -5; 2, 2; 0, 3")
B = np.matrix("3, 1, 0; -1, 0, 2")

In [47]:
np.dot(A, B)

matrix([[  8,   1, -10],
        [  4,   2,   4],
        [ -3,   0,   6]])

In [48]:
np.dot(B, A)

matrix([[  5, -13],
        [ -1,  11]])

In [50]:
A = np.matrix('1,2,3; 4,5,6; 7, 8, 10')
np.linalg.inv(A)

matrix([[-0.66666667, -1.33333333,  1.        ],
        [-0.66666667,  3.66666667, -2.        ],
        [ 1.        , -2.        ,  1.        ]])

In [52]:
# определитель
A = np.matrix ("1, 2, 3; 4, 5, 6 ; 7, 8, 10")
print(np.linalg.det(A))

-2.9999999999999996


In [54]:
A = np.matrix ("2, 0, 0; 0, 1, 0 ; 0, 0, 4")
print(np.linalg.det(A).round())

8.0


In [55]:
round(1/8, 3)

0.125

In [56]:
# ранг
v1 = np.array([1,2,3,1])
v2 = np.array([4,5,6,1])
v3 = np.array([7,8,9,1])
A = np.array([v1, v2, v3]).T
print(np.linalg.matrix_rank(A))

2
